In [6]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [3]:
sent=[
'the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good',]

sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voca_size = 10000
onehot_repr=[one_hot(words,voca_size) for words in sent]
print(onehot_repr)

[[8014, 1139, 4346, 5842], [8014, 1139, 4346, 8528], [8014, 7597, 4346, 4084], [7570, 256, 2549, 7725, 9349], [7570, 256, 2549, 7725, 3654], [9100, 8014, 9491, 4346, 664], [6707, 7443, 857, 7725]]


In [9]:
sent_len=8
embedded_doc = pad_sequences(onehot_repr,padding='pre',maxlen=sent_len)
print(embedded_doc)

[[   0    0    0    0 8014 1139 4346 5842]
 [   0    0    0    0 8014 1139 4346 8528]
 [   0    0    0    0 8014 7597 4346 4084]
 [   0    0    0 7570  256 2549 7725 9349]
 [   0    0    0 7570  256 2549 7725 3654]
 [   0    0    0 9100 8014 9491 4346  664]
 [   0    0    0    0 6707 7443  857 7725]]


In [10]:
dim = 10

model = Sequential()
model.add(Embedding(voca_size,dim,input_length=sent_len))
model.compile('adam','mse')
model.summary()

model.predict(embedded_doc)

c:\Users\shaha\.conda\envs\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step   


array([[[-2.31688507e-02,  1.84050091e-02,  1.01213939e-02,
          2.06594579e-02, -3.75353582e-02,  4.39634807e-02,
         -3.80640849e-02, -9.03623179e-03,  4.81058247e-02,
          3.16415913e-02],
        [-2.31688507e-02,  1.84050091e-02,  1.01213939e-02,
          2.06594579e-02, -3.75353582e-02,  4.39634807e-02,
         -3.80640849e-02, -9.03623179e-03,  4.81058247e-02,
          3.16415913e-02],
        [-2.31688507e-02,  1.84050091e-02,  1.01213939e-02,
          2.06594579e-02, -3.75353582e-02,  4.39634807e-02,
         -3.80640849e-02, -9.03623179e-03,  4.81058247e-02,
          3.16415913e-02],
        [-2.31688507e-02,  1.84050091e-02,  1.01213939e-02,
          2.06594579e-02, -3.75353582e-02,  4.39634807e-02,
         -3.80640849e-02, -9.03623179e-03,  4.81058247e-02,
          3.16415913e-02],
        [ 2.35970728e-02,  4.08330671e-02,  4.65330519e-02,
          2.60093845e-02, -1.39664188e-02, -8.73690844e-03,
         -6.64196908e-04,  4.06666882e-02, -4.473853